let collections = [
    {
        collectionNames: [{ alias: "Clines" }, { alias: "clines" }],
        collectionArtist: "artBoffin",
        collectionId: 1,
        collectionContractAddress: "0xbbfb6e466f376e493da35b5665dbfc19f7204231",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/clines_33581abd3f.png",
        collectionWebsiteSlug: "clines",
        collectionMintedTokens: 4372,
    },
    {
        collectionNames: [{ alias: "Caesium" }, { alias: "caesium" }],
        collectionArtist: "imnotminimal",
        collectionId: 2,
        collectionContractAddress: "0xbbfb6e466f376e493da35b5665dbfc19f7204231",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/caesium_68d41ac782.png",
        collectionWebsiteSlug: "caesium",
        collectionMintedTokens: 3842,
    },
    {
        collectionNames: [{ alias: "Amerkle" }, { alias: "amerkle" }],
        collectionArtist: "Laya Mathikshara",
        collectionId: 10000,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/amerkle_2d8b44c4cc.png",
        collectionWebsiteSlug: "amerkle",
        collectionMintedTokens: 1087,
    },
    {
        collectionNames: [{ alias: "Blóm" }, { alias: "blom" }, { alias: "Blom" }, { alias: "blóm" }],
        collectionArtist: "lucastswick",
        collectionId: 10001,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/blom_88a583499c.png",
        collectionWebsiteSlug: "blom",
        collectionMintedTokens: 1176,
    },
    {
        collectionNames: [{ alias: "qTrees" }, { alias: "qtrees" }, { alias: "qtrees1" }, { alias: "qTrees1" }],
        collectionArtist: "artBoffin",
        collectionId: 10002,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/qtrees1_20ca2a250d.png",
        collectionWebsiteSlug: "qtrees1-valuma",
        collectionMintedTokens: 732,
    },
    {
        collectionNames: [{ alias: "Valuma" }, { alias: "valuma" }],
        collectionArtist: "toiminto",
        collectionId: 10003,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/valuma_1fe8cec08c.png",
        collectionWebsiteSlug: "qtrees1-valuma",
        collectionMintedTokens: 737,
    },
    {
        collectionNames: [{ alias: "Cirque de lumieres" }, { alias: "Cirque" }, { alias: "cirque" }, { alias: "cirque de lumieres" }],
        collectionArtist: "greweb",
        collectionId: 10004,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/lumieres_0219d9d1a9.png",
        collectionWebsiteSlug: "lumieres",
        collectionMintedTokens: 801,
    },
    {
        collectionNames: [{ alias: "Astratta" }, { alias: "astratta" }],
        collectionArtist: "Jos Vromans",
        collectionId: 10005,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/astratta_9d24b760a3.png",
        collectionWebsiteSlug: "astratta",
        collectionMintedTokens: 500,
    },
    {
        collectionNames: [{ alias: "Toha" }, { alias: "toha" }],
        collectionArtist: "Rich Poole",
        collectionId: 10006,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/toha_0631550033.png",
        collectionWebsiteSlug: "toha",
        collectionMintedTokens: 999,
    },
    {
        collectionNames: [{ alias: "Fjäll" }, { alias: "Fjall" }, { alias: "fjall" }, { alias: "fjäll" }],
        collectionArtist: "TΞNGIL",
        collectionId: 10007,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/fjaell_360f5f16c3.png",
        collectionWebsiteSlug: "fjall",
        collectionMintedTokens: 999,
    },
    {
        collectionNames: [{ alias: "Folded Sequence" }, { alias: "folded sequence" }, { alias: "folded" }, { alias: "Folded" }],
        collectionArtist: "toiminto",
        collectionId: 10008,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/folded_sequence_bac3719f8d.png",
        collectionWebsiteSlug: "folded-sequence",
        collectionMintedTokens: 999,
    },
    {
        collectionNames: [{ alias: "Dendrites" }, { alias: "dendrites" }, { alias: "Dendrite" }, { alias: "dendrite" }],
        collectionArtist: "Jens Clarholm",
        collectionId: 10009,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/dendrites_ba15ab6507.png",
        collectionWebsiteSlug: "dendrites",
        collectionMintedTokens: 649,
    },
    {
        collectionNames: [{ alias: "Imagination" }, { alias: "imagination" }],
        collectionArtist: "Hevey",
        collectionId: 10010,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/imagination_cd72a256fd.png",
        collectionWebsiteSlug: "imagination",
        collectionMintedTokens: 837,
    },
    {
        collectionNames: [{ alias: "Anhedra" }, { alias: "anhedra" }],
        collectionArtist: "Nadieh Bremer",
        collectionId: 10011,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/anhedra_727feb9672.png",
        collectionWebsiteSlug: "anhedra",
        collectionMintedTokens: 812,
    },
    {
        collectionNames: [{ alias: "Kakano" }, { alias: "kakano" }],
        collectionArtist: "Rich Poole",
        collectionId: 10012,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/kakano_e5bc3a252d.png",
        collectionWebsiteSlug: "kakano",
        collectionMintedTokens: 1000,
    },
    {
        collectionNames: [{ alias: "Dusk" }, { alias: "dusk" }],
        collectionArtist: "MrHabMo",
        collectionId: 20000,
        collectionContractAddress: "0xdc1b41492db3b485914d92a2e2cfa35fd93fc8ca",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/dusk_6150b8264f.png",
        collectionWebsiteSlug: "dusk",
        collectionMintedTokens: 225,
    },
    {
        collectionNames: [{ alias: "AiLBUMS" }, { alias: "ailbums" }, { alias: "Ailbums" }, { alias: "AIlbums" }],
        collectionArtist: "artBoffin",
        collectionId: 20001,
        collectionContractAddress: "0xe449943fcc09af55a3167405971573bb98749a6f",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/ailbums_70b482e34e.png",
        collectionWebsiteSlug: "ailbums",
        collectionMintedTokens: 209,
    },
    {
        collectionNames: [{ alias: "Tidal Friction" }, { alias: "tidal friction" }, { alias: "Tidal" }, { alias: "tidal" }],
        collectionArtist: "r0zk0",
        collectionId: 10013,
        collectionContractAddress: "0xd8b7cc75e22031a72d7b8393113ef2536e17bde6",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/tidal_friction_84be06b3ad.jpg",
        collectionWebsiteSlug: "tidal-friction",
        collectionMintedTokens: 365,
    },
    {
        collectionNames: [{ alias: "Terroir" }, { alias: "terroir" }],
        collectionArtist: "Kelly Milligan",
        collectionId: 30000,
        collectionContractAddress: "0x5e2a7ea1a13014d7235befe92883cee6c7312287",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/terroir_b8512b563c.jpg",
        collectionWebsiteSlug: "terroir",
        collectionMintedTokens: 650,
    },
    {
        collectionNames: [{ alias: "Closer" }, { alias: "closer" }, { alias: "CLOSER" }],
        collectionArtist: "Dan Zucco",
        collectionId: 20002,
        collectionContractAddress: "0x48836b65f5d919ce6435247de96e3eaf7e6c8919",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/closer_08586b0d1f.jpeg",
        collectionWebsiteSlug: "closer",
        collectionMintedTokens: 100,
    },
    {
        collectionNames: [{ alias: "Hyperscopic" }, { alias: "hyperscopic" }],
        collectionArtist: "Dominikus",
        collectionId: 30001,
        collectionContractAddress: "0x8b8886f48d1bda7db50861a3a5af0477bbaadee0",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/hyperscopic_2a0b407d44.png",
        collectionWebsiteSlug: "hyperscopic",
        collectionMintedTokens: 96,
    },
    {
        collectionNames: [{ alias: "≈3000" }, { alias: "3000" }, { alias: "=3000" }, { alias: "= 3000" }],
        collectionArtist: "Santiago",
        collectionId: 30002,
        collectionContractAddress: "0xba31fe4bcb72fdaadfae65a047b9e9979c628df5",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/3000_212cc2dd96.png",
        collectionWebsiteSlug: "3000",
        collectionMintedTokens: 100,
    },
    {
        collectionNames: [
            { alias: "Rorschach Meadow" },
            { alias: "Rorschach Meadow" },
            { alias: "Rorschach" },
            { alias: "rorschach" },
            { alias: "Meadow" },
            { alias: "Meadows" },
            { alias: "meadow" },
            { alias: "meadows" },
        ],
        collectionArtist: "Ash White",
        collectionId: 20003,
        collectionContractAddress: "0xe667a6ff661507c8ff8b37d094d49cf4fc5c199c",
        collectionIcon: "https://gen-art-public.s3.amazonaws.com/007_1c0d6344fb.png",
        collectionWebsiteSlug: "rorschach-meadow",
        collectionMintedTokens: 63,
    },
];

export default collections;